<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20170809 10:56:18.324" generator="Robot 3.0.2 (Python 2.7.8 on win32)">
<suite source="F:\logs and reports\账户中心" id="s1" name="账户中心">
<suite source="F:\logs and reports\账户中心\艾佳币" id="s1-s1" name="艾佳币">
<suite source="F:\logs and reports\账户中心\艾佳币\艾佳币回收冻结.txt" id="s1-s1-s1" name="艾佳币回收冻结">
<test id="s1-s1-s1-t1" name="当艾佳币冻结的数目超过账户艾佳币的总数目，调用接口，接口返回成功，没有订单号，没有入数据库">
<kw name="参数配置" library="myResource">
<kw name="mysql数据库的连接" library="myResource">
<arguments>
<arg>192.168.1.32</arg>
</arguments>
<kw name="Connect To Database Using Custom Params" library="DatabaseLibrary">
<doc>Loads the DB API 2.0 module given `dbapiModuleName` then uses it to</doc>
<arguments>
<arg>pymysql</arg>
<arg>host='${mysql_host}',port=3306,user='root',passwd='aijia1234567',db='account'</arg>
</arguments>
<msg timestamp="20170809 10:56:18.866" level="INFO">Executing : Connect To Database Using Custom Params : pymysql.connect(db_api_2.connect(host='192.168.1.32',port=3306,user='root',passwd='aijia1234567',db='account')) </msg>
<msg timestamp="20170809 10:56:28.987" level="FAIL">OperationalError: (2003, "Can't connect to MySQL server on '192.168.1.32' (timed out)")</msg>
<status status="FAIL" endtime="20170809 10:56:28.990" starttime="20170809 10:56:18.846"></status>
</kw>
<status status="FAIL" endtime="20170809 10:56:28.994" starttime="20170809 10:56:18.843"></status>
</kw>
<status status="FAIL" endtime="20170809 10:56:28.997" starttime="20170809 10:56:18.841"></status>
</kw>
<status status="FAIL" endtime="20170809 10:56:29.001" critical="yes" starttime="20170809 10:56:18.833">OperationalError: (2003, "Can't connect to MySQL server on '192.168.1.32' (timed out)")</status>
</test>
<test id="s1-s1-s1-t2" name="当艾佳币冻结的数目超过艾佳币余额的数目，调用接口，接口">
<kw name="参数配置" library="myResource">
<kw name="mysql数据库的连接" library="myResource">
<arguments>
<arg>192.168.1.32</arg>
</arguments>
<kw name="Connect To Database Using Custom Params" library="DatabaseLibrary">
<doc>Loads the DB API 2.0 module given `dbapiModuleName` then uses it to</doc>
<arguments>
<arg>pymysql</arg>
<arg>host='${mysql_host}',port=3306,user='root',passwd='aijia1234567',db='account'</arg>
</arguments>
<msg timestamp="20170809 10:56:29.028" level="INFO">Executing : Connect To Database Using Custom Params : pymysql.connect(db_api_2.connect(host='192.168.1.32',port=3306,user='root',passwd='aijia1234567',db='account')) </msg>
<msg timestamp="20170809 10:56:39.032" level="FAIL">OperationalError: (2003, "Can't connect to MySQL server on '192.168.1.32' (timed out)")</msg>
<status status="FAIL" endtime="20170809 10:56:39.035" starttime="20170809 10:56:29.026"></status>
</kw>
<status status="FAIL" endtime="20170809 10:56:39.037" starttime="20170809 10:56:29.023"></status>
</kw>
<status status="FAIL" endtime="20170809 10:56:39.038" starttime="20170809 10:56:29.020"></status>
</kw>
<status status="FAIL" endtime="20170809 10:56:39.040" critical="yes" starttime="20170809 10:56:29.009">OperationalError: (2003, "Can't connect to MySQL server on '192.168.1.32' (timed out)")</status>
</test>
<status status="FAIL" endtime="20170809 10:56:39.044" starttime="20170809 10:56:18.523"></status>
</suite>
<status status="FAIL" endtime="20170809 10:56:39.056" starttime="20170809 10:56:18.516"></status>
</suite>
<status status="FAIL" endtime="20170809 10:56:39.062" starttime="20170809 10:56:18.355"></status>
</suite>
<statistics>
<total>
<stat fail="2" pass="0">Critical Tests</stat>
<stat fail="2" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="2" id="s1" name="账户中心" pass="0">账户中心</stat>
<stat fail="2" id="s1-s1" name="艾佳币" pass="0">账户中心.艾佳币</stat>
<stat fail="2" id="s1-s1-s1" name="艾佳币回收冻结" pass="0">账户中心.艾佳币.艾佳币回收冻结</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
